### ISSUE TITLE
FieldDataPluginTool.exe doesn't work if renamed

### ISSUE THREAD

**Issue by DougSchmidt-AI** [AquaticInformatics/aquarius-field-data-framework#36]
If you rename the `FieldDataPluginTool.exe`, or simply download a second copy as `FieldDataPluginTool (1).exe`, it will fail to launch.

```
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at FieldDataPluginTool.Program.LoadEmbeddedResource(System.String)
   at FieldDataPluginTool.Program.ConfigureLogging()
   at FieldDataPluginTool.Program.Main()
```

Fix the embedded resource resolver so that it doesn't depend upon the assembly filename.

**Comment by DougSchmidt-AI** [comment]
Fixed by #37 in [v18.3.2](https://github.com/AquaticInformatics/aquarius-field-data-framework/releases/tag/v18.3.2)
